- src/tequila/optimizers/__init__.py
- src/tequila/optimizers/_containers.py
- src/tequila/optimizers/optimizer_base.py
- src/tequila/optimizers/optimizer_gd.py
- src/tequila/optimizers/optimizer_gpyopt.py
- src/tequila/optimizers/optimizer_phoenics.py
- src/tequila/optimizers/optimizer_scipy.py
- src/tequila/simulators/simulator_api.py
- src/tequila/simulators/simulator_base.py
- src/tequila/simulators/simulator_cirq.py
- src/tequila/simulators/simulator_pyquil.py
- src/tequila/simulators/simulator_qiskit.py
- src/tequila/tools/qng.py
- tutorials/FAQ.ipynb
- tutorials/Optimizer_Tutorial.ipynb
Can access real devices in pyquil and qiskit, and emualated devices in pyquil, qiskit, and cirq, through the 'device' keyword in simulators, compilers, etc. Backend_options keyword removed from all loci.
> Implementation of device sampling and emulation. 

- src/tequila/optimizers/optimizer_gd.py
- src/tequila/optimizers/optimizer_gpyopt.py
- src/tequila/optimizers/optimizer_scipy.py
- src/tequila/simulators/simulator_cirq.py
- src/tequila/tools/qng.py
Allows (some) customization in use of QNG. Users of optimizers can pass down:
gradient={'method':'qng','function':custom_function" where custom function takes an expectationvalue and compiler arguments, and returns a list of (list of lists), that is to say, the blocks of the QGT.
> Qng change

- requirements.txt
- src/tequila/simulators/simulator_api.py
- src/tequila/simulators/simulator_qulacs_gpu.py
- tests/test_noise.py
- tests/test_noise_opt.py
- tests/test_scipy.py
Hey guys,
I've implemented a qulacs backend gpu backend for a project with Abhinav.
It works on Beluga.
> Add Qulacs GPU backend

- src/tequila/circuit/circuit.py
Pull request for the fork I've been working on. Only change is the addes to_NetworkX() function in the circuit.py file
> Added NetworkX circuit function

- src/tequila/optimizers/optimizer_base.py
- src/tequila/optimizers/optimizer_scipy.py
Hi, we need additional callbacks for optimization. 
- Added support for this in the scipy optimizer.
- Persist args / kwargs in optimizer_base for further modification
> Added callback support for scipy and args/kwargs persistence

- src/tequila/quantumchemistry/__init__.py
s.th. NBodyTensor can be used as tq.chemistry.NBodyTensor instead of tq.chemistry.qc_base......
> load NBodyTensor into chem-init

- src/tequila/wavefunction/qubit_wavefunction.py
- tests/test_simulator_backends.py
* fixed bug in keymap that prevented sample accumulation when mapped to smaller subregister
* added a test for the last commit
> Pr keymap fix (#109)

- src/tequila/__init__.py
- src/tequila/ml/__init__.py
- src/tequila/ml/interface_tf.py
- src/tequila/ml/interface_torch.py
- src/tequila/ml/ml_api.py
- src/tequila/ml/utils_ml.py
- src/tequila/objective/objective.py
- src/tequila/simulators/simulator_base.py
- tests/test_tf_interface.py
- tests/test_torch_interface.py
**Main files of importance for TFLayer to work**: 
- interface_tf.py 
- tequila/\_\_init\_\_.py
- ml/\_\_init\_\_.py
- ml_api.py
- objective.py
_Why the changes in objective.py?_ 
When calling extract_variables() on a VectorObjective, the list returned is unordered, which later on caused problems assigning variables to their respective values. Also, to sort them, \_\_lt\_\_() had to be implemented, so the simplest way I saw to order them was by name (as a string).
**Other files changed to allow sampling**: 
- simulator_base.py (only removed "assert n_samples == samples" on line 441 due to problems when using simulators like simulator_cirq.py, which filtered the count value and made the assertion fail)
**Files added for testing**: 
- test_tf_interface.py
> Tensorflow Layer (TFLayer) added

- .github/workflows/ci_chemistry.yml
- .github/workflows/ci_optimizers.yml
- .github/workflows/ci_phoenics.yml
- README.md
- src/tequila/__init__.py
- src/tequila/apps/__init__.py
- src/tequila/apps/adapt/__init__.py
- src/tequila/apps/adapt/adapt.py
- src/tequila/circuit/compiler.py
- src/tequila/circuit/qpic.py
- src/tequila/quantumchemistry/qc_base.py
- tests/test_adapt.py
Added generalized adaptive solver from https://doi.org/10.1039/D0SC06627C
> PR:AdaptiveSolver

- src/tequila/optimizers/optimizer_scipy.py
> bug fix: scipy wasn't passing noise down

- README.md
- src/tequila/circuit/_gates_impl.py
- src/tequila/circuit/gates.py
- src/tequila/version.py
Implements the alternative four-term parameter shift rule from Appendix F in [this paper](https://arxiv.org/pdf/2005.14475.pdf) where reasonable.
> Pr four term rule

- .github/workflows/ci_backends.yml
- README.md
- src/tequila/simulators/simulator_api.py
- src/tequila/simulators/simulator_qlm.py
- tests/test_noise.py
- tests/test_noise_opt.py
* Created support for QLM (simulators)
> QLM simulator support (#159)

- src/tequila/quantumchemistry/qc_base.py
related issue : (https://github.com/aspuru-guzik-group/tequila/issues/165)
> fixed calculating nvirt

- src/tequila/simulators/simulator_cirq.py
Changed cirq.TrialResult to cirq.Result
> Cirq v0.11.0 compatible

- src/tequila/circuit/circuit.py
- src/tequila/circuit/qpic.py
- src/tequila/objective/objective.py
- src/tequila/quantumchemistry/qc_base.py
small bugfix when adding layers of S or D to UCC circuits: hcb automatically turned off, doubles can be removed now
will unify with madness interface soon
> improved ucc on qc_base

- src/tequila/quantumchemistry/psi4_interface.py
- src/tequila/quantumchemistry/pyscf_interface.py
- src/tequila/quantumchemistry/qc_base.py
- tests/test_chemistry.py
> Pr Chemistry Bug Fixes

- src/tequila/quantumchemistry/chemistry_tools.py
Minor change to allow for capitalization in file paths when loading molecule from a file.
> Support for capitalized filenames

- src/tequila/quantumchemistry/chemistry_tools.py
- src/tequila/quantumchemistry/madness_interface.py
Fix of bug that would cause get_pair_orbitals to sometimes fail when called by local_qubit_map. Suggested by J. Kottmann.
> Minor bugfix of madness interface

- requirements.txt
- src/tequila/quantumchemistry/chemistry_tools.py
- src/tequila/quantumchemistry/madness_interface.py
- tests/test_chemistry_madness.py
> fixing bug in auto-determining core-orbitals

- src/tequila/grouping/binary_rep.py
- src/tequila/grouping/binary_utils.py
- src/tequila/grouping/compile_groups.py
- src/tequila/grouping/overlapping_methods.py
- src/tequila/objective/objective.py
- src/tequila/simulators/simulator_base.py
- tests/test_binary_pauli.py
I messed up the old branch pr-overlapping-groups so I had to create a new branch. Hopefully, I haven't messed up anything. Sorry for any inconvenience.
> Pr overlap groups

- src/tequila/quantumchemistry/qc_base.py
Adding more convenience to Chemistry basis module:
easy initialization of UR and UC circuits as described in https://arxiv.org/abs/2207.12421
> PR Chem Convenience

- src/tequila/apps/krylov/krylov.py
potential trouble maker in the future
> suspicious self import

- .github/workflows/ci_basic_autograd.yml
- src/tequila/objective/objective.py
- src/tequila/quantumchemistry/qc_base.py
to allow more convenience when using jax instead of autograd (osx-arm64 and win)
> changing float_power to power in __pow__ operators

- .github/workflows/ci_backends.yml
- requirements.txt
- src/tequila/simulators/simulator_cirq.py
- tests/test_simulator_backends.py
Closes https://github.com/tequilahub/tequila/issues/307.
> Bugfix: change API to modularized `cirq` package.

- src/tequila/quantumchemistry/pyscf_interface.py
> hofix: no irreps in c1

- src/tequila/optimizers/optimizer_gd.py
- tests/test_noise_opt.py
- tests/test_simulator_backends.py
> fixing issues with gradient printing in spsa

- src/tequila/simulators/simulator_qiskit.py
fixing u1, cu1 deprecation in qiskit
> qiskit u1 --> p

- README.md
- requirements.txt
> Kottmanj patch 4

- README.md
Updated the beta-version website to the now official website of the Tequila Tutorials
> Updated Tutorials-Website

- src/tequila/quantumchemistry/qc_base.py
- tests/test_chemistry.py
Now get_givens_decompositions allow decompostion of an abstract matrix which may contain tq.Variables
> givens decomposition qtensor variables

- src/tequila/quantumchemistry/madness_interface.py
changed floor division to usual division
> maxrank fix
