src/tequila/quantumchemistry/psi4_interface.py, src/tequila/quantumchemistry/qc_base.py
- changed numpy.einsum optimize to greedy
- changed computation of electr. rep. integrals in psi4_interface to molecular integrals
- added class TwoBodyTensor for convenient reordering between openfermion, chemistry and physics convention. This class also can easily be extended for some functionalities needed in expl. corrl. correction scheme, or be of use if dependency on openfermion would be attenuated.
=> MO adjustements

src/tequila/quantumchemistry/qc_base.py
Fix s.th. active spaces can be used without a quantumchemistry backend in qc_base.
=> Active space fix for qc_base. Some typos corrected in qc_base.

tests/test_gd_optimizer.py, tests/test_gpyopt.py, tests/test_scipy.py
This mostly involved selecting parameters closer to optimal values in different optimization tests. This should be especially useful for testing some of the slower backends.
test_scipy could probably be pruned a bit still, some of the tests are probably not actually required...
=> Significantly improved the run times of the test suite

tutorials/BasicUsage.ipynb
In the tutorial BasicUsage.ipynb, measurement is outdated, in this change it is updated with the use of the read_out_qubits keyword
=> Update the way a measurement is made

requirements.txt, src/tequila/simulators/simulator_qibo.py, src/tequila/utils/keymap.py, tests/test_simulator_backends.py
The order you specify the `read_out_qubits` should not matter.
A minimal example replicating the issue:
```python
simulator = 'qiskit'
qc  = tq.gates.X(0)
qc += tq.gates.Z(1)
result = tq.simulate(qc, backend=simulator, samples=1, read_out_qubits=[0, 1])
print(result)
---
Output: +1.0000|10> 
result = tq.simulate(qc, backend=simulator, samples=1, read_out_qubits=[1, 0])
print(result)
---
Output: +1.0000|01> 
```
Similar with Qibo:
```python
simulator = 'qibo'
qc  = tq.gates.X(0)
qc += tq.gates.Z(1)
result = tq.simulate(qc, backend=simulator, samples=1, read_out_qubits=[0, 1])
print(result)
---
Output: +1.0000|01> 
result = tq.simulate(qc, backend=simulator, samples=1, read_out_qubits=[1, 0])
print(result)
---
Output: +1.0000|10> 
```
Expected result is `+1.0000|10>`.
=> Fix a bug with read_out qubits using Qiskit and Qibo simulators

.github/workflows/ci_chemistry.yml, requirements.txt
Prevent crashes when importing pyscf resulting from newest release of h5py
=> PR pyscf hotfix

src/tequila/quantumchemistry/qc_base.py
Fix for #175 
Changed behaviour:
- blank lines in the geometry string are now ignored
- line lengths !=4 do not cause the function to break out early
- line lengths < 4 are now padded with 0.0
=> fix geometry formatting bug in ParametersQC

src/tequila/__init__.py, src/tequila/circuit/gradient.py, src/tequila/objective/__init__.py, src/tequila/objective/qtensor.py, src/tequila/simulators/simulator_api.py, tests/test_qtensor.py
In this PR, I have added a new file `qtensor.py` which contains the class `QTensor`. This class was needed to ease the implementation of mathematical objects like vectors, matrices, and tensors. This class has been derived from `numpy.ndarray` and thus, all the linear algebraic operations that can be performed on an ndarray can be performed on a QTensor object. Besides, applying any function on a QTensor object, compiling, simulating, or taking the grad of a QTensor object can be done in the same way as is done for a tequila objective.
Apart from that, I have also added `test_qtensor.py` file which contains tests for this class. <br> 
For more details on the usage and implementation of QTensor, I have also added two notebooks in `tequila-tutorials`:<br>
1. Tutorial notebook: …
=> added qtensor class

src/tequila/apps/robustness/interval.py, src/tequila/hamiltonian/qubit_hamiltonian.py, src/tequila/ml/interface_torch.py, src/tequila/simulators/simulator_qibo.py
`np.float` and `np.int` does not exist in NumPy anymore.
Code changed to use `np.float64` and `np.int64`.
=> Fix NumPy float and int

src/tequila/circuit/_gates_impl.py, src/tequila/circuit/gates.py, src/tequila/hamiltonian/paulis.py, tests/test_gradient.py
Hi Jakob,
Following our discussion about the `GeneralizedRotation` gate, I have transferred the `shifted_gates` functionality from `QubitExcitation` to `GeneralizedRotation`. This modification allows the `GeneralizedRotation` method to accept generators that do not necessarily have only two eigenvalues of +-r.
=> Refactor `GeneralizedRotation` to generators with (possible) nullspace.

src/tequila/circuit/circuit.py
Currently the `__iadd__` function in `QCircuit` directly appends gates without copying. This means that when adding the same circuit twice, the same gate instances are added twice, instead of two copies.
This leads to unexpected problems, e.g. the following code doesn't work:
```python
import tequila as tq
U = tq.QCircuit()
gate = tq.gates.X(target=0)
U += gate
U += gate
U.add_controls(control=1)
```
This is because `add_controls` tries to add a control to the gate twice, but during the second time fails because the gate already has the control.
Interestingly, since `__add__` is implemented differently, this works:
```python
import tequila as tq
U = tq.QCircuit()
gate = tq.gates.X(target=0)
U = U + gate
U = U + gate
U.add_controls(control=1)
```
I'm not sure what the intended behavior is, …
=> Deepcopy gates in `__iadd__` of `QCircuit`

src/tequila/simulators/simulator_base.py, src/tequila/utils/bitstrings.py, src/tequila/wavefunction/qubit_wavefunction.py
While investigating why the Qulacs backend does not seem to use multiple threads in my code, I noticed that very little time is spent in the actual simulation.
For testing, I used the Quantum Fourier Transform. By running either just a QFT, or a QFT and then an inverse QFT, we can make the resulting wavefunction dense or sparse, which is important for testing the performance.
<details>
<summary>Code</summary>
```python
import tequila as tq
from math import pi
import time
SIZE = 20
def qft(size: int, inverse: bool = False) -> tq.QCircuit():
U = tq.QCircuit()
for i in range(size):
U += tq.gates.H(target=i)
for j in range(size - i - 1):
U += tq.gates.Phase(target=i + j + 1, angle=(-1 if inverse else 1) * pi / 2 ** (j + 2))
U += tq.gates.CRz(target=i, control=i + j + 1, angle=(-1 if inverse …
```
=> Simulation performance improvements

.github/workflows/ci_backends.yml, README.md, src/tequila/simulators/simulator_qiskit.py, src/tequila/utils/bitstrings.py
This is an attempt to update the `simulator_qiskit` code to be compatible with the latest version of Qiskit and Qiskit Aer. I likely did not catch everything, but basic calls to `tq.simulate()` should work.
Using this requires the packages `qiskit`, `qiskit-aer` and `qiskit-ibm-runtime`.
TODO: FakeProvider does not seem to exist anymore, see https://github.com/Qiskit/qiskit/pull/11376, and I wasn't sure what exactly it is used for, so I just commented it out for now.
References for some of the changes I made:
- `bind_parameters` -> `assign_parameters`: https://github.com/Qiskit/qiskit/issues/7057
- `qiskit.providers.ibmq` -> `qiskit_ibm_runtime`: READMEs in https://github.com/Qiskit/qiskit-ibmq-provider and https://github.com/Qiskit/qiskit-ibm-provider
- `qiskit.test.mock` -> …
=> Fix current Qiskit versions

.github/workflows/ci_backends.yml, README.md, src/tequila/simulators/simulator_api.py, src/tequila/simulators/simulator_qiskit.py, src/tequila/simulators/simulator_qiskit_gpu.py, src/tequila/utils/bitstrings.py, tests/test_simulator_backends.py
This pull request depends on https://github.com/tequilahub/tequila/pull/368.
I added support for running the Qiskit simulator on the GPU by creating a subclass that changes the device name. I used the same structure as for the Qulacs GPU simulator.
Using this requires the `qiskit-aer-gpu` package.
I also commented out the package check for `qulacs-gpu`, because that package is not maintained, instead you have to compile Qulacs with GPU support, see https://github.com/qulacs/qulacs/issues/623#issuecomment-2006123134.
=> Add Qiskit GPU simulator

src/tequila/simulators/simulator_api.py, src/tequila/simulators/simulator_base.py, src/tequila/simulators/simulator_qiskit.py, src/tequila/simulators/simulator_qulacs.py, src/tequila/simulators/simulator_qulacs_gpu.py, src/tequila/wavefunction/qubit_wavefunction.py, tests/test_simulator_backends.py
This pull request depends on https://github.com/tequilahub/tequila/pull/370.
For the Qulacs and Qiskit backend, it makes it possible to initialize circuits with arbitrary wavefunctions instead of only basis states.
This also adds the parameter for sampling and to `tq.simulate`.
I have added boolean flags to the backend circuit objects that indicate which backends support this and throw an error message when necessary. This doesn't seem ideal, but I didn't want to change the other backends that I can't test.
Also, combining initial states with a keymap is awkward, I think it only makes sense if we assume that all states on the inactive qubits are the same. For now I disabled it and throw an error message.
I noticed that there's no keymap for sampling, can we get rid of it for simulating …
=> Allow generic wavefunctions as initial_state

src/tequila/objective/objective.py, src/tequila/simulators/simulator_base.py, src/tequila/simulators/simulator_qulacs.py, tests/test_simulator_backends.py
I didn't realize that my previous pull request worked only for directly simulating circuits, not computing expectation values. This should fix that, though I'm still not sure if I caught all the code paths this time.
=> Add initial state support for expectation values

src/tequila/circuit/circuit.py, src/tequila/utils/bitstrings.py, src/tequila/wavefunction/qubit_wavefunction.py
This PR speeds up working with and compiling large circuits.
Here is a simple benchmark to test this:
<details>
<summary>Code</summary>
```python
import tequila as tq
import random
from time import time
if __name__ == "__main__":
random.seed(0)
start = time()
circuit = tq.QCircuit()
for i in range(100):
subcircuit = tq.QCircuit()
for j in range(100):
qubits = random.sample(range(10), 3)
subcircuit += tq.gates.Toffoli(qubits[0], qubits[1], qubits[2])
subcircuit += tq.gates.Ry(0.5, random.choice(range(10)))
circuit += subcircuit
daggered = circuit.dagger()
circuit += daggered
tq.simulate(circuit, backend="qulacs", optimize_circuit=False)
print(f"Time: {time() - start:.3f} s")
```
</details>
Having `optimize_circuit=False` is necessary, without it the Qulacs optimization will take very long. …
=> Improve circuit compilation performance

src/tequila/simulators/simulator_api.py, src/tequila/simulators/simulator_qiskit.py
- The Qiskit noise feature seems to be broken, (temporarily?) removed it from `SUPPORTED_NOISE_BACKENDS`
- I forgot to transpile in my previous pull request which caused the `test_wfn_simple_consistency` test to fail, fixed that (surprisingly, all the other tests seemed fine even without)
- Added a check for `HAS_IBMQ` before testing if a backend is an `IBMBackend` so that the code works without the package installed. (I don't think the IBMQ code is tested though, because it requires an IBMQ account).
=> Remove Qiskit noise feature and transpile circuit

src/tequila/circuit/postselection.py, tests/test_postselection.py
Implements `PostselectionCircuit` which supports `Postselection` operations that project the wavefunction onto the subspace where a specified set of qubits are all in the state |0>.
=> Implement Postselection

src/tequila/quantumchemistry/pyscf_interface.py, src/tequila/quantumchemistry/qc_base.py, tests/test_chemistry.py
Closes #406 
- Modified `compute_fci` function to return the energy and FCI wavefuncion implemented in the pyscf backend.
- Added tests comparing results with `numpy.linalg.eigh` for small molecules.
=> Add FCI wavefunction to pyscf backend

src/tequila/circuit/gates.py, tests/test_recompilation_routines.py, tests/test_scipy.py
Closes #400 
- Modified `compile` method in `QubitExcitationImpl` to support general n-qubit excitations.
- Added tests comparing both fidelity and depth against non-optimized decompositions.
=> Implement optimized compiling for general QubitExcitations beyond single and double

src/tequila/circuit/qpic.py
At the moment, if you use the `export_to` function of the `qpic` module, compiling to a pdf, some output is generated in stdout, i.e.
```
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
restricted \write18 enabled.
entering extended mode
tikz2preview tmpt9x9dxaq.tikz
pdflatex -interaction=batchmode tmpt9x9dxaq.tex
```
The output is not very useful (errors, which would be useful, should go to stderr) and might not be wanted. This PR pipes the stdout of the subprocess to `/dev/null`.
=> Surpress stdout in "export_to"

src/tequila/simulators/simulator_qulacs.py
This changes how the qubit map for hamiltonians is built in Qulacs expectation vaues which should fix a problem with identity gates.
@JdelArco98 Could you check if this solves your issue?
=> Fix Identity Hamiltonian
